name: Publish Extension
on:
  workflow_dispatch: # Manual trigger
    inputs:
      version:
        description: 'Version type to publish'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: contains('["meister"]', github.actor)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for pushing changes
      run: |
        git config --global user.name "Martin Kapp"
        git config --global user.email "martin@coderats.net"

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm install

    - name: Azure Devops Verify PAT
      env:
        VSCE_PAT: ${{ secrets.AZURE_DEVOPS_PAT }} # Access NPM token securely from GitHub Secrets
      run: npm run vsce-verify-pat

    - name: Build and Publish Extension
      env:
        VSCE_PAT: ${{ secrets.AZURE_DEVOPS_PAT }} # Access NPM token securely from GitHub Secrets
      run: |
        echo "Building the package"
        npm run build
        echo "Publishing ${{ github.event.inputs.version }} release"
        git status
        npm run vsce-publish -- ${{ github.event.inputs.version }}

    - name: Push changes back to master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for pushing changes
      run: |
        # Add any changes (e.g., package version bump)
        git add .

        # Commit changes if there are any
        git commit -m "Publish version $TAG_NAME" || echo "No changes to commit"

        # Push changes back to the master branch
        git push --tags
        git push origin master
